### ISSUE TITLE
Error while running 'npm run build'

### ISSUE THREAD

**Issue by mzch** [n1try/anchr#6]
While running 'npm run build', an error occurred. How can I fix this error?

```
Loading "cdnify.js" tasks...ERROR
>> ReferenceError: primordials is not defined
Warning: Task "cdnify" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2019-06-11 06:23:33 UTC-7)
loading tasks             224ms  ▇▇▇▇ 9%
wiredep:app               133ms  ▇▇▇ 5%
wiredep:test               30ms  ▇ 1%
loading grunt-usemin       29ms  ▇ 1%
concurrent:dist           694ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 27%
loading grunt-postcss      35ms  ▇ 1%
postcss:server            233ms  ▇▇▇▇▇ 9%
postcss:dist               42ms  ▇ 2%
concat:generated           84ms  ▇▇ 3%
loading grunt-google-cdn  987ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 38%
Total 2.6s

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! anchr-multi-webservice@0.0.1 build: `cd public && grunt build && cd ..`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the anchr-multi-webservice@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/anchr/.npm/_logs/2019-06-11T13_23_35_790Z-debug.log
```

- /srv/anchr/.npm/_logs/2019-06-11T13_23_35_790Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose config Skipping project config: /srv/anchr/.npmrc. (matches userconfig)
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info lifecycle anchr-multi-webservice@0.0.1~prebuild: anchr-multi-webservice@0.0.1
7 info lifecycle anchr-multi-webservice@0.0.1~build: anchr-multi-webservice@0.0.1
8 verbose lifecycle anchr-multi-webservice@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle anchr-multi-webservice@0.0.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/anchr/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle anchr-multi-webservice@0.0.1~build: CWD: /srv/anchr
11 silly lifecycle anchr-multi-webservice@0.0.1~build: Args: [ '-c', 'cd public && grunt build && cd ..' ]
12 silly lifecycle anchr-multi-webservice@0.0.1~build: Returned: code: 3  signal: null
13 info lifecycle anchr-multi-webservice@0.0.1~build: Failed to exec build script
14 verbose stack Error: anchr-multi-webservice@0.0.1 build: `cd public && grunt build && cd ..`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
14 verbose stack     at EventEmitter.emit (events.js:200:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:200:13)
14 verbose stack     at maybeClose (internal/child_process.js:1021:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
15 verbose pkgid anchr-multi-webservice@0.0.1
16 verbose cwd /srv/anchr
17 verbose Linux 4.19.0-5-amd64
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 verbose node v12.4.0
20 verbose npm  v6.9.0
21 error code ELIFECYCLE
22 error errno 3
23 error anchr-multi-webservice@0.0.1 build: `cd public && grunt build && cd ..`
23 error Exit status 3
24 error Failed at the anchr-multi-webservice@0.0.1 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 3, true ]
```

**Comment by n1try** [comment]
I could reproduce the problem with latest Node version. However, it seems to work with Node 8 and grunt 0.4.5 (grunt-cli 1.3.2).

**Comment by mzch** [comment]
Thanks, I tried Node.js 10 and completed successfully. :)

**Comment by DimuthuKasunWP** [comment]
I tried with changing node versions but it doesn't work for me. Can you guys give me any suggestions?

**Comment by mzch** [comment]
Could you try `npm run build` using Node.js 8.x?
